# Generated by Django 4.1.3 on 2022-11-16 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('avatar', models.ImageField(blank=True, max_length=250, upload_to='')),
                ('slug', models.SlugField(blank=True, max_length=120, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=35, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('image_link', models.CharField(blank=True, max_length=255)),
                ('year_published', models.PositiveSmallIntegerField(blank=True)),
                ('pages', models.PositiveSmallIntegerField(blank=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.author')),
                ('genre', models.ManyToManyField(blank=True, related_name='books', to='book.genre')),
            ],
            options={
                'verbose_name': 'Произведение',
                'verbose_name_plural': 'Произведения',
                'ordering': ['title'],
            },
        ),
    ]
