# Generated by Django 4.1.3 on 2022-11-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitems_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirmation_code',
            field=models.CharField(blank=True, choices=[('email', 'email'), ('phone', 'phone')], max_length=6),
        ),
    ]
