# Generated by Django 4.1.3 on 2022-11-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_confirmation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='confirmation_code',
            field=models.CharField(choices=[('email', 'email'), ('phone', 'phone')], max_length=6),
        ),
    ]
