# Generated by Django 4.1.3 on 2022-11-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
