# Generated by Django 4.1.3 on 2022-11-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0003_remove_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='avatar',
        ),
    ]
