# Generated by Django 4.1.3 on 2022-11-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0004_remove_profileimage_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='carousel_img',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
