# Generated by Django 4.1.3 on 2022-11-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0005_profileimage_carousel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
