# Generated by Django 4.1.3 on 2022-11-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0006_userprofile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='carousel_img',
            new_name='avatar',
        ),
    ]
