# Generated by Django 4.1.3 on 2022-11-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0010_rename_cachback_userprofile_cashback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='profile_image'),
        ),
    ]
