# Generated by Django 4.1.3 on 2022-11-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0011_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cashback',
            field=models.PositiveIntegerField(default=3, verbose_name='cashback'),
        ),
    ]
