# Generated by Django 4.1.3 on 2022-11-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0013_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='collected_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
